services:
  - type: worker
    env: node
    name: scheduled-healthcheck
    buildCommand: "npm install && npm run build"
    startCommand: "node dist/index.js"
    autoDeploy: true
    plan: starter
    envVars:
      - key: TRIGGER_API_KEY
        sync: false
      - key: WEBSITE_URL
        sync: false